GET http://localhost:3001/users

###

POST http://localhost:3001/addUser
Content-Type: application/json

{
  "username": "Test2",
  "password": "Test",
  "email": "test2@testtest.com",
  "subscription": true
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "Test",
  "password": "Test"
}

###

POST http://localhost:3001/admin
Content-Type: application/json

{"password": "Admin"}

###

GET http://localhost:3001/users/62918c4e08662c65350a76c1
Content-Type: application/json

{"_id": "62918c4e08662c65350a76c1"}

###

PUT http://localhost:3001/users/update/628fea39040ebe63204524fd
Content-Type: application/json

{"_id": "62901d1d09fd48d4d9c99af4", "subscription": true}
