GET http://localhost:3001/users

###

POST http://localhost:3001/addUser
Content-Type: application/json

{
  "firstname": "Ayla",
  "username": "Ayla2",
  "password": "Attack",
  "email": "ayla@pawesome.com",
  "subscription": true
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "Ayla",
  "password": "Attack"
}

###

POST http://localhost:3001/admin
Content-Type: application/json

{"password": "Admin"}

###

GET http://localhost:3001/users/Ayla
Content-Type: application/json

{"_id": "628fea39040ebe63204524fd"}